// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujafvexrxepuopgvbepf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqYWZ2ZXhyeGVwdW9wZ3ZiZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjcxMTUsImV4cCI6MjA2OTg0MzExNX0.noc8NTDxAxewdRVpnDfADQ0jKIyUpqAEaWWlZtsrwps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});